server:
  port: 8999
  
eureka:
  instance:
    hostname: localhost
    
spring:
  application:
    name: ApiGetway
  cloud:
    gateway:
       routes:
         - id: ContactService
           uri: lb://ContactService
           predicates:
             - Path=/contact/**
#           filters:
#            - name: CircuitBreaker
#              args:
#                name: ContactService
#                fallbackuri: forward:/ContactServiceFallback
         - id: UserService
           uri: lb://UserService
           predicates:
            - Path=/user/**
#           filters:
#            - name: CircuitBreaker
#              args:
#                name: UserService
#                fallbackuri: forward:/UserServiceFallback
         
  